language: go

go:
  - 1.9
  - "1.10.x"
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' | grep -v /vendor/)
  - PKGS=$(go list ./... | grep -v /vendor/)

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race $PKGS
  - go vet $PKGS
